"""FIRST_MIGRATION

Revision ID: 17b68f9d9346
Revises: 
Create Date: 2024-10-22 20:32:03.888560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pydantic


# revision identifiers, used by Alembic.
revision: str = '17b68f9d9346'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('STUDENTS_DETAILS',
    sa.Column('NAMES', sa.String(length=30), nullable=False),
    sa.Column('GENDERS', sa.String(length=10), nullable=False),
    sa.Column('AGES', sa.Integer(), nullable=False),
    sa.Column('SCHOOL_NAMES', sa.String(length=30), nullable=False),
    sa.Column('STANDARDS', sa.Integer(), nullable=False),
    sa.Column('SECTIONS', sa.String(length=2), nullable=False),
    sa.Column('ROLL_NUMBERS', sa.Integer(), nullable=False),
    sa.Column('CONTACT_NUMBERS', sa.BIGINT(), nullable=False),
    sa.Column('PERCENTAGES', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('CONTACT_NUMBERS')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('STUDENTS_DETAILS')
    # ### end Alembic commands ###
